MAX_AGE_DISABILTY = 60
MIN_INCOME_DISABILTY = 0

FIRST_AGE_LIMIT_DEDUCTION = 30
LAST_AGE_LIMIT_DEDUCTION = 40

FIRST_RISK_DEDUCTION_BY_AGE = -2
LAST_RISK_DEDUCTION_BY_AGE = -1

MIN_INCOME_TO_RISK_DEDUCTION = 200000
RISK_REDUCTION_BY_MIN_INCOME = -1

VEHICLE_AGE_TO_INCREASE_RISK = 5
RISK_INCREASE_BY_VEHICLE_AGE = 1

MIN_DEPENDENTS_TO_INCREASE_RISK = 1
RISK_INCREASE_BY_DEPENDENTS = 1

RISK_QUESTIONS_QTD = 3

RISK_INCREASE_BY_MORTGAGED = 1

MARITAL_STATUS_INCREASER = 'married'
RISK_INCREASE_BY_MARITAL_STATUS = 1

RISK_PARAMETERS_POINTS = {'lower' : 0, 'greater': 3}
