from config import FIRST_AGE_LIMIT_DEDUCTION, LAST_AGE_LIMIT_DEDUCTION, FIRST_RISK_DEDUCTION_BY_AGE, LAST_RISK_DEDUCTION_BY_AGE
def risk_by_age(age):
    if age < FIRST_AGE_LIMIT_DEDUCTION:
        return FIRST_RISK_DEDUCTION_BY_AGE

    if age >= FIRST_AGE_LIMIT_DEDUCTION and age <= LAST_AGE_LIMIT_DEDUCTION:
        return LAST_RISK_DEDUCTION_BY_AGE
    return 0
